version: '3.4'

admin_server:
  build:
    context: ./admin_server
    dockerfile: Dockerfile.development
  container_name: admin_server
  ports:
    - 5000:5000
  restart: always
  volumes:
    - ./admin_server:/var/www/html/admin_server
    - /var/www/html/admin_server/node_modules
  env_file: 
    - ./admin_server/.env.development